### ISSUE TITLE
No such module 'LoopKit'

### ISSUE THREAD

**Issue by nhabbott** [LoopKit/CGMBLEKit#121]
Upon attempting to build the app to my iPhone 7, a Swift Complier Error appears saying that is cannot find the LoopKit module in Glucose+SensorDisplayable.swift

**Comment by mrengy** [comment]
I am having the same issue building to an iPhone SE. How did you resolve this error?

<img width="993" alt="No Such Module Loopkit error" src="https://user-images.githubusercontent.com/2223603/72349490-9cba0b80-36aa-11ea-8eee-ca908f6e5293.png">

**Comment by mrengy** [comment]
I found the solution under "Build Error" at https://seemycgm.com/2018/05/03/reset-g5-transmitter/

Then I got an error of `xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH` but resolved it with https://stackoverflow.com/a/41536029/370407

**Comment by JackHowa** [comment]
there's the wayback machine for the dead link: https://seemycgm.com/2018/05/03/reset-g5-transmitter/

https://web.archive.org/web/20180716161328/https://seemycgm.com/2018/05/03/reset-g5-transmitter/
